(async function(){
  const checks=[];
  const check=(name,ok)=>{checks.push({name,pass:!!ok});if(!ok)throw Error(name);};
  try{
    check('App runs on secure local virtual host',location.origin==='https://deadmanshand.example'&&isSecureContext);
    localStorage.setItem('desktop-test-probe','persistent');
    check('Desktop settings storage available',localStorage.getItem('desktop-test-probe')==='persistent');
    localStorage.removeItem('desktop-test-probe');
    const initialConfirm=window.confirm;window.confirm=()=>true;document.getElementById('reset').click();window.confirm=initialConfirm;
    document.getElementById('reveal-animation').checked=false;document.getElementById('reveal-animation').dispatchEvent(new Event('change',{bubbles:true}));
    check('Arsenal and acquisition controls removed',!document.getElementById('arsenal-dialog')&&!document.getElementById('arsenal-open')&&!document.getElementById('acquisition')&&!document.getElementById('setup-notice'));
    const initial=ChaosApp.getState().profile;
    check('Purchase mode automatic with no inventory',initial.acquisition==='purchase'&&Object.keys(initial.owned).length===0);
    check('Standard weapons automatically available',initial.unlocked.length===167&&!initial.unlocked.includes('burgess'));
    const rank=document.getElementById('rank');rank.value='100';rank.dispatchEvent(new Event('change',{bubbles:true}));
    const qm=document.getElementById('quartermaster');if(!qm.checked)qm.click();
    check('Quartermaster works inside EXE',ChaosApp.getState().profile.traits.includes('quartermaster'));
    document.getElementById('seed').value='desktop-smoke';
    await ChaosApp.roll();
    const state=ChaosApp.getState();
    await Promise.all(Array.from(document.querySelectorAll('.equipment-image'),img=>img.decode()));
    check('Every dealt item displays its equipment image',document.querySelectorAll('.equipment-image').length===state.builds.slice(0,state.buildCount).reduce((n,b)=>n+b.slots.filter(Boolean).length,0)&&Array.from(document.querySelectorAll('.equipment-image')).every(img=>img.naturalWidth>0));
    const images=await Promise.all(ChaosEngine.data.items.map(item=>new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img.naturalWidth>0);img.onerror=()=>resolve(false);img.src=item.image;})));
    check('All 251 embedded equipment images decode offline',images.length===251&&images.every(Boolean));
    check('Native packaged app generates valid loadout',ChaosEngine.validate(state.slots,state.profile).valid);
    check('Every item charged at full purchase price',ChaosApp.exportObject().validation.cost===state.slots.filter(Boolean).reduce((sum,id)=>sum+ChaosEngine.byId.get(id).price,0));
    check('Packaged export produces valid JSON data',JSON.parse(JSON.stringify(ChaosApp.exportObject())).validation.valid);
    check('Copy button available',!document.getElementById('copy').disabled&&!!navigator.clipboard);
    check('Save button available',!document.getElementById('export').disabled);
    const first=state.slots[0];document.querySelector(`[data-hunter="${ChaosApp.getState().activeBuild}"][data-lock="0"]`).click();
    await ChaosApp.roll();
    check('Held weapon retained inside EXE',ChaosApp.getState().slots[0]===first);
    document.getElementById('clear-locks').click();
    document.querySelector('[data-build-count="3"]').click();
    await ChaosApp.roll();
    const trio=ChaosApp.getState();
    check('Trio deals three valid independent builds',trio.buildCount===3&&trio.profile.team==='trio'&&trio.builds.every(b=>ChaosEngine.validate(b.slots,trio.profile).valid)&&new Set(trio.builds.map(b=>JSON.stringify(b.slots))).size===3);
    check('All three hunter loadouts are visible',document.querySelectorAll('.hunter-loadout').length===3&&document.querySelectorAll('.weapon-card').length===6&&document.querySelectorAll('.equipment-card').length===24);
    const panels=[...document.querySelectorAll('.hunter-loadout')].map(p=>p.getBoundingClientRect());
    check('Trio loadouts sit side by side',panels.every(p=>Math.abs(p.top-panels[0].top)<2)&&panels[2].right<=innerWidth);
    const exported=ChaosApp.exportObject();
    check('Team export includes all hunters',exported.builds.length===3&&exported.builds.every(b=>b.validation.valid));
    document.querySelector('[data-build="1"]').click();
    const secondWeapon=ChaosApp.getState().slots[0];
    document.querySelector(`[data-hunter="${ChaosApp.getState().activeBuild}"][data-lock="0"]`).click();
    document.querySelector('[data-build="0"]').click();
    check('Locks belong to individual hunters',!ChaosApp.getState().locks[0]);
    await ChaosApp.roll();
    document.querySelector('[data-build="1"]').click();
    check('Team reroll keeps second hunter lock',ChaosApp.getState().slots[0]===secondWeapon&&ChaosApp.getState().locks[0]);
    document.getElementById('clear-locks').click();
    document.getElementById('seed').value='repeatable-team';await ChaosApp.roll();
    const repeated=JSON.stringify(ChaosApp.getState().builds.map(b=>b.slots));await ChaosApp.roll();
    check('Team seed is reproducible',JSON.stringify(ChaosApp.getState().builds.map(b=>b.slots))===repeated);
    document.querySelector('[data-build-count="2"]').click();await ChaosApp.roll();
    check('Duo deals and exports exactly two builds',ChaosApp.getState().buildCount===2&&ChaosApp.exportObject().builds.length===2);
    const beforeFailure=JSON.stringify(ChaosApp.getState().builds.map(b=>b.slots));
    const budget=document.getElementById('budget');budget.value='0';budget.dispatchEvent(new Event('change',{bubbles:true}));await ChaosApp.roll();
    check('Failed team deal preserves every hand and disables export',JSON.stringify(ChaosApp.getState().builds.map(b=>b.slots))===beforeFailure&&document.getElementById('export').disabled);
    budget.value='';budget.dispatchEvent(new Event('change',{bubbles:true}));await ChaosApp.roll();
    const saved=JSON.parse(localStorage.getItem('dead-mans-hand.v1'));
    check('Team selection and all builds persist',saved.buildCount===2&&saved.builds.length===3&&saved.activeBuild===1);
    check('Desktop hand fits without scrolling',document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth);
    const frame=document.createElement('iframe');frame.style.cssText='position:fixed;inset:0;border:0;width:1366px;height:768px;z-index:50';
    await new Promise(resolve=>{frame.onload=resolve;frame.src=location.href;document.body.append(frame);});
    const restored=frame.contentWindow.ChaosApp.getState();
    check('Reload restores team, selected hunter and cards',restored.buildCount===2&&restored.activeBuild===1&&JSON.stringify(restored.builds.map(b=>b.slots))===JSON.stringify(ChaosApp.getState().builds.map(b=>b.slots)));
    check('1366 by 768 laptop fits without scrolling ('+frame.contentDocument.documentElement.scrollWidth+' x '+frame.contentDocument.documentElement.scrollHeight+')',frame.contentDocument.documentElement.scrollHeight<=768&&frame.contentDocument.documentElement.scrollWidth<=1366);
    frame.contentDocument.querySelector('[data-build-count="3"]').click();await frame.contentWindow.ChaosApp.roll();
    check('Laptop shows all three complete loadouts together',frame.contentDocument.querySelectorAll('.hunter-loadout').length===3&&[...frame.contentDocument.querySelectorAll('.hunter-loadout')].every(p=>p.getBoundingClientRect().bottom<=768)&&frame.contentDocument.documentElement.scrollWidth<=1366);
    const teamSelect=frame.contentDocument.getElementById('team');teamSelect.value='duo';teamSelect.dispatchEvent(new frame.contentWindow.Event('change',{bubbles:true}));
    check('Hunting with selector updates visible squad size',frame.contentWindow.ChaosApp.getState().buildCount===2&&frame.contentDocument.querySelectorAll('.hunter-loadout').length===2);
    for(const [width,height] of [[1920,1080],[2560,1440]]){
      frame.style.width=width+'px';frame.style.height=height+'px';
      for(const count of [1,2,3]){
        frame.contentDocument.querySelector(`[data-build-count="${count}"]`).click();await frame.contentWindow.ChaosApp.roll();
        const doc=frame.contentDocument, shell=doc.querySelector('.site-shell').getBoundingClientRect(), board=doc.querySelector('.workspace').getBoundingClientRect(), footer=doc.querySelector('footer').getBoundingClientRect();
        check(`${width}x${height} ${count} hunters fill maximized window`,Math.abs(shell.width-width)<2&&Math.abs(footer.bottom-height)<2&&board.bottom>=height-60&&doc.documentElement.scrollWidth<=width&&doc.documentElement.scrollHeight<=height);
        const columns=[...doc.querySelectorAll('.hunter-loadout')].map(p=>p.getBoundingClientRect());
        check(`${width}x${height} loadouts stretch evenly`,columns.length===count&&columns.every(p=>Math.abs(p.top-columns[0].top)<2&&Math.abs(p.bottom-columns[0].bottom)<2)&&columns[0].height>height*.5);
      }
    }
    frame.style.width='390px';frame.style.height='844px';await new Promise(resolve=>setTimeout(resolve,100));
    check('390px mobile fits without horizontal scrolling',frame.contentDocument.documentElement.scrollWidth<=390);
    check('Mobile build selector stays visible',frame.contentWindow.getComputedStyle(frame.contentDocument.querySelector('.squad-bar')).position==='sticky');
    frame.remove();
    document.querySelector('[data-build-count="1"]').click();await ChaosApp.roll();
    document.querySelector('[data-build-count="1"]').click();
    check('Selecting current build count keeps valid exports',!document.getElementById('export').disabled);
    document.querySelector('[data-build-count="3"]').click();await ChaosApp.roll();
    const editHunter=(field,index,value)=>{const input=document.querySelector(`[data-hunter-${field}="${index}"]`);input.value=value;input.dispatchEvent(new Event('change',{bubbles:true}));};
    const beforeNames=JSON.stringify(ChaosApp.getState().builds.map(b=>b.slots));
    editHunter('name',0,'Alice');editHunter('name',1,'Bob <&>');editHunter('name',2,'Charlie');
    check('Names update safely without invalidating gear',!document.getElementById('export').disabled&&document.querySelector('[data-build="1"]').textContent==='Bob <&>'&&JSON.stringify(ChaosApp.getState().builds.map(b=>b.slots))===beforeNames);
    editHunter('rank',0,'1');await ChaosApp.roll();editHunter('rank',1,'50');
    check('Rank change invalidates only its hunter',!ChaosApp.getState().builds[0].dirty&&ChaosApp.getState().builds[1].dirty&&!ChaosApp.getState().builds[2].dirty&&document.getElementById('export').disabled);
    editHunter('rank',2,'100');
    for(const invalid of ['0','101','1.5','']){editHunter('rank',2,invalid);check('Reject invalid rank '+JSON.stringify(invalid),ChaosApp.getState().builds[2].rank===100);}
    await ChaosApp.roll();
    const named=ChaosApp.getState(),namedExport=ChaosApp.exportObject();
    check('Each hunter rolls and exports its own rank',namedExport.builds.every((b,i)=>b.rank===[1,50,100][i]&&b.profile.rank===b.rank&&b.validation.valid&&ChaosEngine.validate(named.builds[i].slots,b.profile).valid));
    check('Names survive rerolls and exports',namedExport.builds.map(b=>b.name).join('|')==='Alice|Bob <&>|Charlie');
    document.querySelector('[data-build-count="1"]').click();document.querySelector('[data-build-count="3"]').click();
    check('Hidden hunters retain name and rank',ChaosApp.getState().builds[2].name==='Charlie'&&ChaosApp.getState().builds[2].rank===100);
    const identityFrame=document.createElement('iframe');identityFrame.style.display='none';
    await new Promise(resolve=>{identityFrame.onload=resolve;identityFrame.src=location.href;document.body.append(identityFrame);});
    check('Names and individual ranks survive reload',identityFrame.contentWindow.ChaosApp.getState().builds.every((b,i)=>b.name===named.builds[i].name&&b.rank===named.builds[i].rank));identityFrame.remove();
    document.querySelector('[data-mode="crazy"]').click();await ChaosApp.roll();
    check('Go Crazy has its own selectable mode',ChaosApp.getState().profile.mode==='crazy'&&document.querySelector('[data-mode="crazy"]').getAttribute('aria-pressed')==='true'&&ChaosApp.exportObject().builds.every(b=>b.validation.valid));
    check('Free item, ammo and hunter rerolls are removed',!document.querySelector('[data-reroll],[data-ammo-reroll],[data-reroll-hunter]'));
    check('Every hunter has a Loadout Mulligan button',document.querySelectorAll('[data-loadout-mulligan]').length===3);
    const beforeSlot=ChaosApp.getState();document.querySelector('[data-loadout-mulligan="1"]').click();const afterSlot=ChaosApp.getState();
    check('Loadout mulligan removes one item and preserves teammates',afterSlot.builds[1].loadoutMulligans===1&&afterSlot.builds[1].slots.filter(Boolean).length===beforeSlot.builds[1].slots.filter(Boolean).length-1&&JSON.stringify(afterSlot.builds[0])===JSON.stringify(beforeSlot.builds[0])&&JSON.stringify(afterSlot.builds[2])===JSON.stringify(beforeSlot.builds[2]));
    check('Next loadout mulligan displays the larger loss',document.querySelector('[data-loadout-mulligan="1"]').textContent.includes('Lose 2'));
    editHunter('rank',1,'49');check('Stale loadout mulligan is disabled',document.querySelector('[data-loadout-mulligan="1"]').disabled);
    await ChaosApp.roll();
    const beforeTraits=ChaosApp.getState();
    document.querySelector('[data-hunter-traits="1"]').click();
    const selectedQM=document.querySelector('#all-traits [data-trait="quartermaster"]');selectedQM.click();
    const changedTraits=ChaosApp.getState();
    check('Traits edit only the selected hunter',changedTraits.builds[1].traits.includes('quartermaster')!==beforeTraits.builds[1].traits.includes('quartermaster')&&JSON.stringify(changedTraits.builds[0].traits)===JSON.stringify(beforeTraits.builds[0].traits)&&JSON.stringify(changedTraits.builds[2].traits)===JSON.stringify(beforeTraits.builds[2].traits));
    check('Trait edits invalidate only their hunter',changedTraits.builds[1].dirty&&!changedTraits.builds[0].dirty&&!changedTraits.builds[2].dirty);
    document.getElementById('traits-dialog').close();
    document.querySelector('[data-build="0"]').click();
    check('Hunter selector refreshes sidebar traits',document.getElementById('quartermaster').checked===ChaosApp.getState().builds[0].traits.includes('quartermaster')&&document.getElementById('hunter-settings-title').textContent==='Alice');
    check('Changed traits require a fresh squad deal',document.querySelector('[data-loadout-mulligan="1"]').disabled);
    await ChaosApp.roll();
    const hunterHeld=ChaosApp.getState().builds[1].slots[0];document.querySelector('[data-lock="0"][data-hunter="1"]').click();document.querySelector('[data-loadout-mulligan="1"]').click();
    const heldAfter=ChaosApp.getState().builds[1];check('Loadout mulligan holds preserve gear unless it is lost',heldAfter.slots[0]===hunterHeld||heldAfter.slots[0]===null&&!heldAfter.locks[0]);if(heldAfter.slots[0])document.querySelector('[data-lock="0"][data-hunter="1"]').click();
    const setOption=(id,value)=>{const field=document.getElementById(id);field.value=value;field.dispatchEvent(new Event('change',{bubbles:true}));};
    document.getElementById('squad-options-open').click();
    setOption('intensity','mild');await ChaosApp.roll();check('Mild chaos includes healing for every hunter',ChaosApp.getState().builds.slice(0,3).every(b=>b.slots.includes('first-aid-kit')));
    setOption('intensity','cursed');setOption('challenge','bows');await ChaosApp.roll();
    check('Squad bow challenge affects all hunters',ChaosApp.getState().builds.every(b=>b.slots[0]==='hunting-bow')&&!document.getElementById('export').disabled);
    document.getElementById('assign-roles').click();
    const conflicting=JSON.stringify(ChaosApp.getState().builds.map(b=>b.slots));await ChaosApp.roll();
    check('Conflicting role and challenge preserve all hands and explain failure',document.getElementById('export').disabled&&!document.getElementById('messages').hidden&&JSON.stringify(ChaosApp.getState().builds.map(b=>b.slots))===conflicting);
    setOption('challenge','none');await ChaosApp.roll();
    check('Automatic squad roles produce valid complementary builds',ChaosApp.getState().builds.map(b=>b.role).join(',')==='sniper,close,support'&&ChaosApp.exportObject().builds.every(b=>b.validation.valid));
    const banned=ChaosApp.getState().builds[0].slots[0];document.getElementById('bans-open').click();
    document.querySelector(`[data-ban="${banned}"]`).click();document.getElementById('bans-dialog').close();await ChaosApp.roll();
    check('UI bans exclude items across the team',ChaosApp.getState().profile.excluded.includes(banned)&&ChaosApp.getState().builds.every(b=>!b.slots.includes(banned)));
    document.getElementById('custom-ammo').click();
    for(let n=0;n<6;n++){document.getElementById('seed').value='custom-squad-'+n;await ChaosApp.roll();if(ChaosApp.getState().builds.some(b=>b.ammo.some(Boolean)))break;}
    check('Custom ammo appears and is included in exported totals',ChaosApp.getState().builds.some(b=>b.ammo.some(Boolean))&&ChaosApp.exportObject().builds.every(b=>b.validation.valid&&b.validation.cost===b.slots.filter(Boolean).reduce((sum,item)=>sum+ChaosEngine.byId.get(item.id).price,0)+b.ammo.reduce((sum,a)=>sum+a.cost,0)));
    const copyText=ChaosApp.exportTeamText();
    check('Copied squad includes each hunters traits role and ammo',copyText.includes('Alice')&&copyText.includes('Bob <&>')&&copyText.includes('Quartermaster')&&copyText.includes('Role: sniper')&&ChaosApp.exportObject().builds.some(b=>b.ammo.some(a=>a.id&&copyText.includes(a.name))));
    check('Ammo has no free reroll button',!document.querySelector('[data-ammo-reroll]'));
    document.getElementById('unique-weapons').click();await ChaosApp.roll();
    check('Uniqueness toggle deals distinct teammate weapons',ChaosApp.getState().profile.uniqueWeapons&&ChaosEngine.uniqueWeapons(ChaosApp.getState().builds)&&!document.getElementById('export').disabled);
    document.querySelector('[data-loadout-mulligan="1"]').click();document.querySelector('[data-mulligan="0"][data-hunter="0"]').click();
    check('Loadout and item mulligans preserve teammate uniqueness',ChaosEngine.uniqueWeapons(ChaosApp.getState().builds)&&!document.getElementById('export').disabled);
    document.getElementById('squad-options-dialog').close();
    document.getElementById('library-open').click();document.getElementById('favorite-name').value='Test squad <&>';document.getElementById('favorite-save').click();
    const favoriteState=ChaosApp.getState(),savedLibrary=JSON.parse(localStorage.getItem('dead-mans-hand.library.v1')),favoriteId=savedLibrary.favorites[0].id;
    check('Favorites save full squads and safely display names',savedLibrary.favorites[0].label==='Test squad <&>'&&document.querySelector('#library-favorites b').textContent==='Test squad <&>');
    document.getElementById('library-dialog').close();document.querySelector('[data-loadout-mulligan="1"]').click();
    document.getElementById('library-open').click();document.querySelector(`[data-restore="${favoriteId}"]`).click();
    check('Favorite restores equipment ammo traits roles ranks names holds and bans',JSON.stringify(ChaosApp.getState().builds)===JSON.stringify(favoriteState.builds)&&JSON.stringify(ChaosApp.getState().profile)===JSON.stringify(favoriteState.profile));
    const archive=JSON.parse(localStorage.getItem('dead-mans-hand.library.v1'));
    check('History is recorded and bounded',archive.history.length>1&&archive.history.length<=30);
    const savedFrame=document.createElement('iframe');savedFrame.style.display='none';await new Promise(resolve=>{savedFrame.onload=resolve;savedFrame.src=location.href;document.body.append(savedFrame);});
    savedFrame.contentDocument.getElementById('library-open').click();
    check('Favorites and new settings survive reload',savedFrame.contentDocument.querySelector(`[data-restore="${favoriteId}"]`)!==null&&savedFrame.contentWindow.ChaosApp.getState().builds.every((b,i)=>Object.keys(favoriteState.builds[i]).every(key=>JSON.stringify(b[key])===JSON.stringify(favoriteState.builds[i][key])))&&savedFrame.contentWindow.ChaosApp.getState().profile.customAmmo);
    savedFrame.remove();
    document.getElementById('library-open').click();document.querySelector(`[data-delete-save="${favoriteId}"]`).click();check('Favorites can be deleted',!JSON.parse(localStorage.getItem('dead-mans-hand.library.v1')).favorites.some(e=>e.id===favoriteId));document.getElementById('library-dialog').close();
    const originalConfirm=window.confirm;window.confirm=()=>true;document.getElementById('reset').click();window.confirm=originalConfirm;
    check('Reset clears all team builds and returns to solo',ChaosApp.getState().buildCount===1&&ChaosApp.getState().activeBuild===0&&JSON.parse(localStorage.getItem('dead-mans-hand.v1')).builds.every(b=>b.slots.every(id=>id===null)&&b.locks.every(v=>!v)));
    document.querySelector('[data-build-count="3"]').click();await ChaosApp.roll();
    check('Reveal starts after a deal',matchMedia('(prefers-reduced-motion: reduce)').matches||document.querySelectorAll('.reveal-pending').length>0);
    check('Slot reels cycle images and finish on the actual item',matchMedia('(prefers-reduced-motion: reduce)').matches||[...document.querySelectorAll('.slot-reel')].length===30&&[...document.querySelectorAll('.slot-reel')].every(r=>r.querySelectorAll('.slot-reel-item').length>=12&&r.querySelector('.slot-reel-item:last-child span').textContent===r.parentElement.querySelector('h3').textContent&&r.querySelector('.slot-reel-strip').getAnimations().length===1));
    const beforeSkip=JSON.stringify(ChaosApp.getState().builds);
    document.getElementById('skip-reveal').click();
    check('Skipping removes all reels without changing the result',!document.querySelector('.slot-reel')&&JSON.stringify(ChaosApp.getState().builds)===beforeSkip);
    check('Skip immediately reveals the complete squad',!document.querySelector('.reveal-pending')&&document.getElementById('skip-reveal').hidden);
    document.getElementById('unique-weapons').click();await ChaosApp.roll(true);
    check('Roulette chooses a feasible challenge for unique teammates',['no-scopes','budget300'].includes(ChaosApp.getState().profile.challenge)&&ChaosEngine.uniqueWeapons(ChaosApp.getState().builds)&&!document.getElementById('export').disabled);
    await new Promise(resolve=>setTimeout(resolve,2400));
    check('Reveal completes automatically',!document.querySelector('.reveal-pending')&&document.getElementById('skip-reveal').hidden);
    document.getElementById('reveal-animation').click();await ChaosApp.roll();
    check('Reveal can be disabled',!document.querySelector('.reveal-pending')&&!ChaosApp.getState().profile.revealAnimation&&!document.getElementById('export').disabled);
    const preMulligan=ChaosApp.getState();
    document.querySelector('[data-mulligan="3"][data-hunter="1"]').click();
    const postMulligan=ChaosApp.getState();
    check('Mulligan removes one item from the chosen hunter',postMulligan.builds[1].mulligan&&postMulligan.builds[1].slots.filter(Boolean).length===preMulligan.builds[1].slots.filter(Boolean).length-1);
    check('Mulligan preserves teammates',JSON.stringify(postMulligan.builds[0])===JSON.stringify(preMulligan.builds[0])&&JSON.stringify(postMulligan.builds[2])===JSON.stringify(preMulligan.builds[2]));
    check('Mulligan hand remains exportable',!document.getElementById('export').disabled&&ChaosApp.exportObject().builds[1].validation.valid);
    const lost=postMulligan.builds[1].slots.findIndex((id,i)=>!id&&preMulligan.builds[1].slots[i]);
    check('Lost slot has no item action',!document.querySelector(`[data-mulligan="${lost}"][data-hunter="1"]`)&&!document.querySelector('[data-reroll]'));
    const lossFrame=document.createElement('iframe');lossFrame.style.display='none';await new Promise(resolve=>{lossFrame.onload=resolve;lossFrame.src=location.href;document.body.append(lossFrame);});
    const restoredLoss=lossFrame.contentWindow.ChaosApp.getState().builds[1];
    check('Mulligan losses survive reload without invalidating the hand',restoredLoss.mulligan&&!restoredLoss.dirty&&JSON.stringify(restoredLoss.slots)===JSON.stringify(postMulligan.builds[1].slots));lossFrame.remove();
    for(let loss=1;loss<=3;loss++){
      const before=ChaosApp.getState();document.querySelector('[data-loadout-mulligan="1"]').click();const after=ChaosApp.getState();
      check('Loadout mulligan pays '+loss+' items',after.builds[1].loadoutMulligans===loss&&after.builds[1].slots.filter(Boolean).length===before.builds[1].slots.filter(Boolean).length-loss);
      check('Previous losses and teammates survive loadout mulligan '+loss,after.builds[1].slots.every((id,n)=>before.builds[1].slots[n]||!id)&&JSON.stringify(after.builds[0])===JSON.stringify(before.builds[0])&&JSON.stringify(after.builds[2])===JSON.stringify(before.builds[2]));
    }
    check('Unaffordable loadout mulligan is disabled',document.querySelector('[data-loadout-mulligan="1"]').disabled);
    const countFrame=document.createElement('iframe');countFrame.style.display='none';await new Promise(resolve=>{countFrame.onload=resolve;countFrame.src=location.href;document.body.append(countFrame);});
    check('Escalating counter survives reload',countFrame.contentWindow.ChaosApp.getState().builds[1].loadoutMulligans===3&&countFrame.contentDocument.querySelector('[data-loadout-mulligan="1"]').disabled);countFrame.remove();
    await ChaosApp.roll();
    check('Fresh squad deal resets mulligan losses and counters',ChaosApp.getState().builds.every(b=>!b.mulligan&&b.loadoutMulligans===0&&b.slots.slice(2).every(Boolean)));
    window.desktopSmokeResult={status:'PASS',checks};
  }catch(error){window.desktopSmokeResult={status:'FAIL',error:error.message,checks};}
})();

